import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { AiOutlineLine } from "react-icons/ai";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Global Learning</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>

      {/* SECTION 1 */}

      <section className={styles.section1}>
        <h1>
          Unlock Your Potential, Embrace the Future <br />{" "}
          <span>Your Journey Starts Here</span>
        </h1>
      </section>

      {/* SECTION 2 */}

      <section className={styles.section2}>
        <AiOutlineLine className={styles.line} />
        <h2>Our Programs</h2>

        <div className={styles.subsec1}>
          <div className={styles.program}>
            <div className={styles.imagebox}>
              <img src="/law.jpg" alt="" />
            </div>
            <div className={styles.textbox}>
              <h2>Law Studies</h2>
            </div>
          </div>
          <div className={styles.program}>
            <div className={styles.imagebox}>
              <img src="/philosophy.jpg" alt="" />
            </div>
            <div className={styles.textbox}>
              <h2>Philosophy</h2>
            </div>
          </div>
          <div className={styles.program}>
            <div className={styles.imagebox}>
              <img src="/medical.jpg" alt="" />
            </div>
            <div className={styles.textbox}>
              <h2>Medical Studies</h2>
            </div>
          </div>
          <div className={styles.program}>
            <div className={styles.imagebox}>
              <img src="/engenier.avif" alt="" />
            </div>
            <div className={styles.textbox}>
              <h2>Civil Engineering</h2>
            </div>
          </div>
          <div className={styles.program}>
            <div className={styles.imagebox}>
              <img src="/computersc.jpg" alt="" />
            </div>
            <div className={styles.textbox}>
              <h2>Computer Science</h2>
            </div>
          </div>
        </div>
      </section>

      {/* SECTION 3 */}

      <section className={styles.section3}>
        <h2>Top-ranked academics and career preparation</h2>
        <div className={styles.subsec2}>
          <button className={styles.sec3btn}>Programs of Study</button>
          <button className={styles.sec3btn}>Academic Schools</button>
          <button className={styles.sec3btn}>Career Services</button>
        </div>
      </section>

      {/* SECTION 4 */}

      <section className={styles.section4}>
        <div className={styles.textarea}>
          <h2>
            About &nbsp; <span>Global Learning</span>{" "}
          </h2>
          <p>
            At Global Learning, we believe in fostering a dynamic and inclusive
            learning environment that empowers our students to achieve their
            full potential. Our faculty is dedicated to providing a world-class
            education, combining academic excellence with practical experiences.
            As a college, we embrace diversity and promote a strong sense of
            community, allowing students from all backgrounds to thrive and grow
            together.{" "}
          </p>
          <button className={styles.learnmorebtn}>learn more</button>
        </div>
        <div className={styles.imagearea}>
          <img src="/heroback.jpg" alt="" />
        </div>
      </section>

      {/* SECTION 5 */}

      <section className={styles.section5}>
        <h2>
          Our &nbsp; <span>Foundation</span>
        </h2>
        <div className={styles.subsec3}>
          <div className={styles.value}>
            <h2>Excellence in Education</h2>
            <p>
              Global Learning achieves its ideal of excellence in undergraduate,
              graduate, and professional education by actively engaging each
              student through exemplary teaching and distinctive learning
              opportunities.
            </p>
            <button className={styles.readmorebtn}>Read more</button>
          </div>
          <div className={styles.value}>
            <h2>Excellence in Education</h2>
            <p>
              Global Learning achieves its ideal of excellence in undergraduate,
              graduate, and professional education by actively engaging each
              student through exemplary teaching and distinctive learning
              opportunities.
            </p>
            <button className={styles.readmorebtn}>Read more</button>
          </div>
          <div className={styles.value}>
            <h2>Excellence in Education</h2>
            <p>
              Global Learning achieves its ideal of excellence in undergraduate,
              graduate, and professional education by actively engaging each
              student through exemplary teaching and distinctive learning
              opportunities.
            </p>
            <button className={styles.readmorebtn}>Read more</button>
          </div>
        </div>
      </section>
    </>
  );
}
